### ISSUE TITLE
to decrease build time, sources should be in separate src/ folder

### ISSUE THREAD

**Issue by jwaldmann** [ndmitchell/derive#15]
The derive.cabal spec contains executable and library. When `cabal install`, (most) library files are recompiled. This wastes time.

The executable should depend on the library, then recompilation is avoided.
This only works when the sources are in a separate directory. 

(I don't know why, and I think this is seriously underdocumented, but I know it from experience.)

It is a trivial change to make, I can do it.

**Comment by ndmitchell** [comment]
Go for it. Although given your other large pending change, I suggest you either wait til after that, or do this change first then merge into that one.

**Comment by ndmitchell** [comment]
I saw your changes and liked them, so merged them all over - so this is now fixed. Thanks!
