### ISSUE TITLE
Fails to build under newest derive

### ISSUE THREAD

**Issue by jkoppel** [ndmitchell/derive#23]
[50 of 62] Compiling Data.Comp.Derive ( src/Data/Comp/Derive.hs, dist/build/Data/Comp/Derive.o )

src/Data/Comp/Derive.hs:73:24: Not in scope: ‘A.makeFunctor’

---------

This wouldn't be such a large problem, except that I failed to install an old derive, because it requires an old mtl

**Comment by ndmitchell** [comment]
Which version of GHC are you using?

**Comment by ndmitchell** [comment]
Oh, `makeFunctor` has disappeared - it's no longer supported in the latest Derive. Just using `deriving Functor` from GHC.

**Comment by jkoppel** [comment]
Oh, whoops, I opened this issue on the wrong project. :blush:
